### ISSUE TITLE
Unable to connect to world [Nukkit 0.15.0]

### ISSUE THREAD

**Issue by MSMegaron** [Nukkit/Nukkit#872] opened 2016-06-22 22:08 UTC
In MCPE or Windows 10 Edition, i can't connect in to my server, in cmd it looks fine, without errors.

**Comment by File14** [comment] 2016-06-22 22:08
Update to latest Nukkit?

**Comment by MSMegaron** [comment] 2016-06-22 22:10
Yeah, i downloaded the latest version few minutes ago

**Comment by Snake1999** [comment] 2016-06-22 23:41
Win10 in a full-bug "client". Try join with android or iOS, if same thing happen, send the issue again.

**Comment by Tee7even** [comment] 2016-06-23 13:19
Stop closing issues just because "it's win10". W10E is almost the same as MCPE. It has some differences and *some* known flaws, but closing issues just because it's allegedly "bugged client"?

**Comment by File14** [comment] 2016-06-23 16:28
@Snake1999 Actually it's not that buggy, it works great in Singleplayer. So this means that Nukkit is the issuse. 

But as @Tee7even reported I can tell that it does work to connect with Windows 10 Pocket Edition. So you can close this issuse.

**Comment by archie426** [comment] 2016-10-06 16:01
Yeah, it is like saying don't run kernel on Linux (i have just made this up and use this as an example, i have no idea what i am talking about, xD) because it is buggy, well it is still an issue and they deserve as much support (unless off-topic, which it isn't) as anyone else with an issue. Got a tired hand

**Comment by archie426** [comment] 2016-10-07 19:33
Thanks

**Comment by Muqsit** [comment] 2016-10-07 19:52
There were no Win10 optimizations so this was expected? The issue is better close I guess

**Comment by archie426** [comment] 2016-10-08 07:04
I thought there was, u getting mixed up with Pocketmine

**Comment by Snake1999** [comment] 2016-11-10 16:11
Go on try this again at 0.16, if any more errors, please post a new issue
We've made a big change since 0.15(months ago!)

**Closed by Snake1999** 2016-11-10 16:11 UTC
