### ISSUE TITLE
Cheat max-players in Multicraft

### ISSUE THREAD

**Issue by iagomcs** [Nukkit/Nukkit#1282] opened 2016-11-16 20:09 UTC
#### Issue description
Customers can cheat the max-players limit in Multicraft. Isn't a Multicraft bug or problem, it don't happens in SpigotMC or Craftbukkit.

#### Steps to reproduce the issue
1. Start server in Multicraft.
2. Download server.proprierts via FTP.
3. Edit max-players option and upload to FTP.
4. use /reload command on console
Glitch done.

#### OS and versions

* Nukkit: Any
* PHP: Any
* Server OS: Any
* Game version:  Any

**Comment by Snake1999** [comment] 2016-11-17 07:32
Reload without restarting is an awesome feature of Nukkit, instead of Spigot or Craftbukkit, we can reload everything. This feature is what the authors of Multicraft didn't expected.
This problem might be fixed by editing Nukkit or Multicraft. We stuff will have a discussion on it, or maybe our stuff can contact developers of multicraft to find out the solution.
We'll keep watching on this. But personally speaking, if your hosting service are really badly crashly affected by this, I personally suggest what you can **temporary**  do now is (one method of following methods is enough):
1. Write a plugin or edit Nukkit code or edit Nukkit permission sheet to disable command `/reload` 
2. Edit Multicraft itself to avoid "reload" string being put into command shell
3. Edit Multicraft to make an enhancement that, if player count > limit, kill the process forcefully

**Comment by Creeperface01** [comment] 2016-11-17 08:34
i think its always possible thrugh reflections, and you can not disable it because nukkit uses reflections too

**Comment by Creeperface01** [comment] 2016-11-17 08:35
its almost impossible to prevent this. plugins can change query player count too.

**Comment by fromgate** [comment] 2016-11-17 10:43
Are you serious? 

**/reload** command is used to reload server. As plugins developer I didn't recommend to use this command but it is not a cheat.
But anyway:

- When server reloading it must reload configuration files.
- If server owner need to change max player online after reload he must be able to make it.
- If hosting provider didn't like this feature he must solve it locally: create plugin, make server.properties file accessible only through  web-interface. You don't need to limit everyone when you need to limit only your customers.

**Comment by Creeperface01** [comment] 2016-11-17 12:09
or limit CPU and RAM instead of players count

**Comment by iagomcs** [comment] 2016-11-17 22:40
@Creeperface01 
About have more players with plugins i've made a system with mcapi.ca to check every server and search for servers with more peoples than max permitied.

**Comment by Creeperface01** [comment] 2016-11-18 08:12
But how do you Check it? By query?

**Comment by iagomcs** [comment] 2016-11-18 12:10
@Creeperface01 yes, just a simple system to take all ip's on multicraft database, post url https://mcapi.ca/query/($serverip)/mcpe and read players (online/max) if online >offline save on another database and i check later.

**Comment by Creeperface01** [comment] 2016-11-18 12:41
But plugins can modify query result

**Comment by iagomcs** [comment] 2016-11-18 12:49
Nah, max players can modify if player use server.proprierts to have more players, if they use plugins query result will be 20/10 not 20/20.

i've tested :P

**Comment by Creeperface01** [comment] 2016-11-18 12:50
Probably not properly, There is query regenrrate event and there plugins can modify all query values

**Comment by Creeperface01** [comment] 2016-11-18 12:55
You can set even current players count,  not only max

**Comment by Creeperface01** [comment] 2016-11-18 12:59
Also we can change whole network interface so it is possible even without this event

**Comment by Creeperface01** [comment] 2016-11-18 13:00
And this is not a bug, but nukkit feature

**Comment by Musda** [comment] 2016-11-19 10:13
You can try this
[https://github.com/Musda-MCPE/Nukkit-Multicraft](url)
:D

**Comment by Creeperface01** [comment] 2016-11-19 10:17
Doesnt exist

**Comment by Musda** [comment] 2016-11-19 10:18
copy & paste

**Comment by Musda** [comment] 2016-11-20 08:28
Has the problem been solved?

**Comment by JackboyPlay** [comment] 2016-11-29 17:04
Give your customers CPU and Ram and not a player limit...

**Comment by MrPowerGamerBR** [comment] 2016-11-29 17:14
@JackboyPlay is right, why limit the player count instead of limiting the RAM/CPU use?

**Comment by Creeperface01** [comment] 2016-11-29 17:18
Me too

**Comment by Snake1999** [comment] 2016-12-02 14:29
```
@JackboyPlay is right, why limit the player count instead of limiting the RAM/CPU use?
```
I agree.

**Closed by Snake1999** 2016-12-02 14:29 UTC
Labels: Progress: Confirmed

**Comment by kennethgomad02** [comment] 2017-07-23 08:21
how to run nukkit in multicraft are there .conf?
