### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by wsj7178** [Nukkit/Nukkit#1255] opened 2016-11-04 13:26 UTC
### Issue description

error when player join

### Steps to reproduce the issue

1. ... use nukkit version before this commit https://github.com/Nukkit/Nukkit/commit/7d86abf6927286930190819450aa90e244288eca
2. ... join and get experience
3. ... update nukkit http://ci.mengcraft.com:8080/job/nukkit/501/
4. ... join!

### OS and versions

* Nukkit: http://ci.mengcraft.com:8080/job/nukkit/501/
* OS: Ubuntu 15
* Device: Ubuntu

### Crashdump, backtrace or other files

```
[ALERT] java.lang.IllegalArgumentException: Value 11.0 exceeds the range!
        at cn.nukkit.entity.Attribute.setValue(Attribute.java:144)
        at cn.nukkit.entity.Attribute.setValue(Attribute.java:138)
        at cn.nukkit.Player.sendAttributes(Player.java:1471)
        at cn.nukkit.Player.processLogin(Player.java:1780)
        at cn.nukkit.Player.authenticateCallback(Player.java:1615)
        at cn.nukkit.Player.tryAuthenticate(Player.java:1604)
        at cn.nukkit.Player.onPlayerPreLogin(Player.java:1597)
        at cn.nukkit.Player.handleDataPacket(Player.java:1921)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:981)
        at cn.nukkit.Server.tickProcessor(Server.java:788)
        at cn.nukkit.Server.start(Server.java:767)
        at cn.nukkit.Server.<init>(Server.java:458)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

```

**Comment by MagicDroidX** [comment] 2016-11-05 07:08
@boybook Please help

**Comment by File14** [comment] 2016-11-05 07:10
I keep getting this when people hit one of my NPCs.

`[ALERT] java.lang.IllegalArgumentException: VarInt too big
	at cn.nukkit.utils.VarInt._readVarInt(VarInt.java:73)
	at cn.nukkit.utils.VarInt.readUnsignedVarInt(VarInt.java:97)
	at cn.nukkit.utils.VarInt.readVarLong(VarInt.java:105)
	at cn.nukkit.utils.BinaryStream.getVarLong(BinaryStream.java:315)
	at cn.nukkit.utils.BinaryStream.getEntityId(BinaryStream.java:335)
	at cn.nukkit.network.protocol.InteractPacket.decode(InteractPacket.java:21)
	at cn.nukkit.network.Network.processBatch(Network.java:151)
	at cn.nukkit.Player.handleDataPacket(Player.java:1834)
	at org.itxtech.synapseapi.SynapsePlayer.handleDataPacket(SynapsePlayer.java:434)
	at org.itxtech.synapseapi.SynapseEntry.handleDataPacket(SynapseEntry.java:344)
	at org.itxtech.synapseapi.network.SynapseInterface.handlePacket(SynapseInterface.java:79)
	at org.itxtech.synapseapi.network.SynapseInterface.process(SynapseInterface.java:53)
	at org.itxtech.synapseapi.SynapseEntry.tick(SynapseEntry.java:236)
	at org.itxtech.synapseapi.SynapseEntry$Ticker.run(SynapseEntry.java:218)
	at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
	at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:204)
	at cn.nukkit.Server.tick(Server.java:989)
	at cn.nukkit.Server.tickProcessor(Server.java:788)
	at cn.nukkit.Server.start(Server.java:767)
	at cn.nukkit.Server.<init>(Server.java:458)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)
`

**Comment by yescallop** [comment] 2016-11-05 10:04
@File14 Fixed your issue in #1259. Next time please open a new issue

**Comment by File14** [comment] 2016-11-05 10:26
Thanks! :D

**Comment by Snake1999** [comment] 2016-11-05 10:55
Confirm again as #1259 merged :) @wsj7178

**Comment by yescallop** [comment] 2016-11-05 11:36
@Snake1999 @wsj7178 It didn't fix this issue at all, it just fixed @File14's

**Comment by yescallop** [comment] 2016-11-05 11:37
I'm trying to fix it

**Comment by Pub4Game** [comment] 2016-11-05 11:43
@yescallop Stop the flood. Do, but don't need to write about it a thousand times

**Comment by yescallop** [comment] 2016-11-05 13:35
Update your Nukkit to latest and retry

**Comment by imjack** [comment] 2016-11-05 13:44
Dupe of #1223 a fast fix is it change the max value of the level to a high number although I'm not sure this is a permanent fix

**Closed** 2016-11-06 01:41 UTC
