### ISSUE TITLE
Timeout server and can't join server.

### ISSUE THREAD

**Issue by UNIvErSeKO** [Nukkit/Nukkit#1821] opened 2017-07-27 17:03 UTC
### Issue Description

Before start, I'm korean, so i weak engilsh.
When my server join my phone, freeze 'locating sever', and out app.
I try reload and save-all and join, but I can't join this server
But, I'm not connect wi-fi. I try connect cellular data, because, I try wifi connect. Wifi conncet is also not.

### OS and Versions

* Nukkit Version: ?? 

* Java Version: 
Newest version
* Host Configuration: 
I7 -3???, 12gb ram 

| Item | Value |
|:----:|:-----:|
| Host OS | win 10 |  
| Memory(RAM) | 12GB | 
| Storage Size | 500 GB | 
| Storage Type | HDD | 
| CPU Type | I7-3??? | 
| CPU Core Count | 4 cores 8 threads | 
| Upstream Bandwidth | 500Mbps | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | android | 
| Client Version | 1.1.4 | 

### Crashdump, Backtrace or Other Files

```
<!--- Copy and paste your backtrace here... -->
```

**Comment by ScraM-Team** [comment] 2017-07-28 02:34
I think this is a duplicate of #1764 (client can't reconnect). 

(There is an issue preventing all new players from connecting: #1817 .  However, that only happens after the server has been up for a while with many users, not what you are describing.)

**Comment by kazuemon** [comment] 2017-07-28 06:38
I am suffering from the same symptoms
I am troubled by getPlayer() being null

**Comment by PeratX** [comment] 2017-08-23 04:58
#1764

**Closed by PeratX** 2017-08-23 04:58 UTC
