### ISSUE TITLE
A strange problem

### ISSUE THREAD

**Issue by ZephyrThomasY** [Nukkit/Nukkit#1872] opened 2017-08-21 09:23 UTC
when i exists a EntiyZombie , There will be a emerald floating on the head of zombie

**Comment by ZephyrThomasY** [comment] 2017-08-21 09:24
sorry...   a typo       Line 1   EntityZombie

**Comment by ZephyrThomasY** [comment] 2017-08-21 09:27
emmmm.   someone told me , when he added a entitypacket ,  there will be a emerald floating

**Comment by ZephyrThomasY** [comment] 2017-08-21 09:32
emmm , perhaps when we add a entitypacket ,there will be a emend floating

**Comment by PeratX** [comment] 2017-08-21 10:10
What the hell? Any images?

**Comment by sero583** [comment] 2017-08-22 12:46
@PeratX I think he means that thing what used to be a bug for a short time on pocketmine forks, where the players had a emeraled a little bit over their head. I think this lies on wrong Entity flag settings

**Comment by PeratX** [comment] 2017-08-22 14:25
Maybe the NBT tags?

**Comment by sero583** [comment] 2017-08-22 16:18
@PeratX I dont think so, on pocketmine forks entities used to have also a bug which was that a the leap (if the player wants to carry on with a mob that item I mean) was directed to the spawn and that also was caused afaik by wrong data flag settings

**Comment by PeratX** [comment] 2017-08-22 16:20
So did they fix that?

**Comment by sero583** [comment] 2017-08-22 18:16
@PeratX yes on every PM fork I know its fixed since a long time. Also I do not know if this is caused by plugin(s) or MCPE because for me everything works fine. Since he said EntityZombie and not like a basic user just Zombie I think maybe it's a class from his plugin. I would just say it's his fault. Closing this issue would be the best option because I do not found anything, also we got no MCPE version, nukkit version or anything else described.

**Closed** 2017-08-22 19:53 UTC
